parameters:
    # nothing to declare
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ecosystem\BusProducerBundle\Service\:
        resource: '../src/Service'

    Ecosystem\BusProducerBundle\Processor\:
        resource: '../src/Processor'

    Ecosystem\BusProducerBundle\Message\:
        resource: '../src/Message'
