parameters:
    # nothing to declare
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ecosystem\BusProducerBundle\Service\:
        resource: '../src/Service'

    Ecosystem\BusProducerBundle\Library\:
        resource: '../src/Library'
