parameters:
    # nothing to declare
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ecosystem\BusProducerBundle\Library\:
        resource: '../src/Library'
        
    Ecosystem\BusProducerBundle\Message\:
        resource: '../src/Message'
